channels:
- conda-forge
dependencies:
- python=3.11.1
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.2.1
  - psutil==5.9.8
  - scikit-learn==1.5.2
  - scipy==1.12.0
name: mlflow-env
